### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sindizzy** [derekantrican/Winforms-Calendar#9]
Absolutely love this control. It looks great and is fast to render.
I have one request if you have time. In my project I only use the MonthView control and not the Calendar control.
Essentially I use it to display the users yearly schedule in summary. The issue arises because the MonthView and Calendar are attached. I can use a "fake" calendar to create CalendarItems and it works. Ive made other small tweaks and it looks like this
![image](https://user-images.githubusercontent.com/5298460/98027716-b14ec800-1dd2-11eb-916e-71a53e94cb74.png)

My last step is to serialize the users CalendarItems on unload and then deserialize them on load. Well since it requires a Calendar it breaks. Anyway I thought that might be a good addition.

**Comment by hieuvn** [comment]
@sindizzy: can you share how to add calendar item to monthview, thank you.

**Comment by sindizzy** [comment]
The Calendar and MonthView are connected. The code is on the main page https://github.com/derekantrican/Winforms-Calendar
